# Moments Application Configuration

# Source folders for hydrating catalogs
catalogs:
  companies:
    name: "Companies"
    description: "AI startup companies and enterprises"
    source_folders:
      - ./companies
    default_folder: ./companies
    file_patterns:
      - "*.md"
      - "*.mdx"
      - "*.png"
      - "*.jpg"
      - "*.jpeg"
      - "*.webp"
      - "*.svg"
    # File system persistence settings
    persistence_mode: "file_primary" # file_primary | memory_primary | hybrid
    auto_sync: true # automatically sync changes to filesystem
    cache_enabled: true # use localStorage for performance caching
    cache_ttl_seconds: 3600 # cache time-to-live
    
  technologies:
    name: "Technologies"
    description: "AI technologies, frameworks, and tools"
    source_folders:
      - ./technologies
    default_folder: ./technologies
    file_patterns:
      - "*.md"
      - "*.mdx"
      - "*.png"
      - "*.jpg"
      - "*.jpeg"
      - "*.webp"
      - "*.svg"
    # File system persistence settings
    persistence_mode: "file_primary" # file_primary | memory_primary | hybrid
    auto_sync: true # automatically sync changes to filesystem
    cache_enabled: true # use localStorage for performance caching
    cache_ttl_seconds: 3600 # cache time-to-live
      
  moments:
    name: "Moments"
    description: "Pivotal business moments extracted and analyzed by AI"
    source_folders:
      - ./moments
    default_folder: ./moments
    file_patterns:
      - "*.md"
      - "*.mdx"
    metadata_format: "frontmatter" # yaml frontmatter for moment metadata
    # File system persistence settings
    persistence_mode: "file_primary" # file_primary | memory_primary | hybrid
    auto_save: true # automatically save analyzed moments to files
    auto_sync: true # automatically sync changes to filesystem
    sync_mode: "bidirectional" # file ↔ memory sync
    cache_enabled: true # use localStorage for performance caching
    cache_ttl_seconds: 3600 # cache time-to-live

# Global persistence settings
persistence:
  # Primary storage strategy: file_system_first | local_storage_first | hybrid
  strategy: "file_system_first"
  
  # Cache settings for performance optimization
  cache:
    enabled: true
    default_ttl_seconds: 3600
    max_size_mb: 50
    
  # File system settings
  file_system:
    auto_sync: true # automatically sync changes between memory and files
    backup_enabled: true # create backup files before overwriting
    compression_enabled: false # compress stored data (not implemented yet)
    
  # Local storage settings (used for temporary cache only when file_system_first)
  local_storage:
    used_for: ["session_cache", "temporary_data", "performance_optimization"]
    clear_on_startup: false # whether to clear cache on app startup
    versioning: true # use versioned storage for migration support

# Application settings
app:
  name: "Moments"
  description: "AI Business Intelligence Dashboard"
  version: "0.1.0"
  
  # Data processing settings
  processing:
    max_file_size_mb: 10
    cache_enabled: true
    cache_ttl_seconds: 3600
    
  # UI settings
  ui:
    items_per_page: 20
    enable_search: true
    enable_filters: true
    
# Moment classification factors
factors:
  micro:
    - company
    - competition
    - partners
    - customers
    
  macro:
    - economic
    - geo_political
    - regulation
    - technology
    - environment
    - supply_chain
    
# Sub-agent configurations
agents:
  content_analyzer:
    enabled: true
    model: "claude-sonnet-4-20250514"
    temperature: 0.3
    
  classification_agent:
    enabled: true
    model: "claude-sonnet-4-20250514"
    temperature: 0.2
    
  correlation_engine:
    enabled: true
    model: "claude-sonnet-4-20250514"
    temperature: 0.4
    
  report_generator:
    enabled: true
    model: "claude-sonnet-4-20250514"
    temperature: 0.5